from spaceone.dashboard.model.domain_dashboard_model import DomainDashboard
from spaceone.dashboard.model.project_dashboard_model import ProjectDashboard
from spaceone.dashboard.model.widget_dashboard_model import WidgetDashboard