from test.factory.domain_dashboard_factory import DomainDashboardFactory
from test.factory.project_dashboard_factory import ProjectDashboardFactory
from test.factory.widget_dashboard_factory import WidgetFactory