from spaceone.dashboard.manager.domain_dashboard_manager import DomainDashboardManager
from spaceone.dashboard.manager.project_dashboard_manager import ProjectDashboardManager
from spaceone.dashboard.manager.custom_widget_manager import CustomWidgetManager